name = "NetworkReduction"
uuid = "8d6c9889-004b-5ffc-a588-babdd84958c6"
authors = ["Germán Morales-España <german.morales@tno.nl>", " Juan Giraldo Chavarriaga <juan.giraldo@tno.nl>", " Muhammad Numan <muhammad.numan@ucd.ie>", " Ni Wang <ni.wang@tno.nl>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"

HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"

JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SCIP = "82193955-e24f-5292-bf16-6f2c5261a85f"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
XLSX = "fdbf4ff8-1666-58a4-91e7-1b58723a45e0"

[compat]
CSV = "0.10"
DataFrames = "1"
Ipopt = "1"
JuMP = "1"
MathOptInterface = "1"
Statistics = "1"
XLSX = "0.10"
julia = "1.10"
